# Generated by Django 3.1.6 on 2021-02-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_base_calendar_motif_occurrence_planning_rule_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
