# Generated by Django 3.1.6 on 2021-04-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='user',
        ),
    ]
