# Generated by Django 3.1.6 on 2021-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('RECCURENCE', 'OUVERTURE RECCURENTE'), ('EXCEPTION', 'OUVERTURE EXCEPTIONNELLE')], default='EXCEPTION', max_length=50),
        ),
    ]
