# Generated by Django 3.1.6 on 2021-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='mon', max_length=32),
            preserve_default=False,
        ),
    ]
