# Generated by Django 3.1.6 on 2021-02-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210211_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='active',
        ),
    ]
