# Generated by Django 3.1.6 on 2021-04-05 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
