# Generated by Django 3.1.6 on 2021-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210406_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
