# Generated by Django 3.1.6 on 2021-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210415_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motif',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='motif',
            name='duration_max',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='motif',
            name='duration_min',
            field=models.DurationField(),
        ),
    ]
