# Generated by Django 3.1.6 on 2021-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210415_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motif',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='motif',
            name='duration_max',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='motif',
            name='duration_min',
            field=models.TimeField(),
        ),
    ]
